
version: '3.4'

services:
  ingest:
    image: open-f1-ingest
    build:
      context: .
      dockerfile: OpenF1.Data.Ingest/Dockerfile
      args:
        - configuration=Debug
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
