
version: '3.4'

services:
  ingest:
    image: open-f1-ingest
    build:
      context: .
      dockerfile: OpenF1.Data.Ingest/Dockerfile
    profiles: ["ingest"]
    environment:
      - OPEN_F1_DB_CONNECTION_STRING="Host=db;Database=OPEN_F1;Username=postgres;Password=changeit"
  
  db:
    image: postgres:15
    ports:
      - 51000:5432
    profiles: ["db"]
    volumes:
      - ~/.local/share/open-f1/data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_PASSWORD: changeit
      POSTGRES_DB: OPEN_F1

  grafana:
    image: grafana/grafana-enterprise
    profiles: ["dashboard"]
    ports:
      - 3000:3000
    volumes:
      - ~/.local/share/open-f1/grafana:/var/lib/grafana:rw
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
