
version: '3.4'

services:
  ingest:
    image: open-f1-ingest
    build:
      context: .
      dockerfile: OpenF1.Data.Ingest/Dockerfile
    profiles: ["ingest"]
    environment:
      - OPEN_F1_DATA_PATH=/data/timing-data.db
    volumes:
      # Mount the local open-f1 working dir to the containers working dir 
      #mso that databases are persisted correctly on the local machine
      - ~/.local/share/open-f1:/data:rw

  grafana:
    image: grafana/grafana-enterprise
    profiles: ["dashboard"]
    ports:
      - 3000:3000
    volumes:
      - ~/.local/share/open-f1/grafana:/var/lib/grafana:rw
      - ~/.local/share/open-f1:/var/data:rw
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource

